import { afterEach, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { openDb } from "../src/db/index.ts";
import { migrateDelivery } from "../src/db/migrations/005-delivery.ts";
import { repo } from "../src/db/repo.ts";
import { deliveryRepo } from "../src/db/delivery-repo.ts";
import { deliveryCoordinationRepo } from "../src/db/delivery-coordination-repo.ts";
import { deriveDeliveryProgress } from "../src/model/delivery-progress.ts";
import { parseEvidenceResult, parseFinishContract } from "../src/model/delivery-coordination.ts";
import { resultTemplate, coordinationAssignment } from "../src/ui/coordination-handoff.ts";
import { reviewDeliveryDocument, collectDeliveryContext } from "../src/model/delivery-context.ts";
import { tempDir, AT } from "./helpers.ts";

const homes: string[] = [], dbs: DatabaseSync[] = [];
const home = () => { const p = tempDir("coordination-"); homes.push(p); return p; };
afterEach(() => { for (const db of dbs.splice(0)) { try { db.close(); } catch { /* Already closed during restart test. */ } } for (const p of homes.splice(0)) fs.rmSync(p, { recursive: true, force: true }); });
const goal = { goal: "A controlled onboarding pilot", intendedUser: "Synthetic members", workflow: "Complete a bounded enrollment", stage: "Fixture prototype", provider: null, model: null, consent: null };
const contract = { outcome: "One bounded pilot", exclusions: ["No live data"], criteria: [{ text: "A member completes enrollment", milestones: [2] }, { text: "An unauthorized member is denied", milestones: [2] }], prerequisites: [] };
const draft = { assumptions: ["Fixture evidence only"], milestones: ["Guided enrollment", "Staff correction", "Operational recovery"].map((title, i) => ({ title, outcome: `Users finish ${title}`, whyNow: "Required for the bounded outcome", scope: ["Whole workflow and recovery"], exclusions: [], acceptance: ["An authorized user finishes", "A denied user cannot proceed"], sourceIds: [], humanPrerequisites: [], dependencies: i ? [i - 1] : [] })) };
function setup() {
  const dir = home(), db = openDb(dir); dbs.push(db);
  const id = repo(db).ensureProject(path.join(dir, "project"), "Synthetic enrollment", AT);
  const legacy = deliveryRepo(db), coordination = deliveryCoordinationRepo(db);
  legacy.saveGoal(id, 0, goal);
  coordination.saveContract(id, 1, contract);
  const state = coordination.saveManualPlan(id, 2, JSON.stringify(draft));
  return { dir, db, id, legacy, coordination, state };
}
function passing(f: ReturnType<typeof setup>) {
  let data = f.coordination.read(f.id);
  const next = deriveDeliveryProgress(data.state, data.coordination).next!;
  data = f.coordination.handoff(f.id, data.state.revision, next.milestone.id);
  const handoff = data.coordination.handoffs.find(h => h.milestoneId === next.milestone.id)!;
  const report = resultTemplate(f.id, handoff);
  report.outcome = "Observed synthetic success";
  report.criteria.forEach(c => { c.status = "met"; c.evidence = "Human observed the fixture scenario in an isolated browser"; });
  report.commands = [{ command: "npm test", exitCode: 0, evidence: "Fixture command output: all scenarios passed" }];
  return { data, report, handoff };
}
function acceptNext(f: ReturnType<typeof setup>) {
  const { data, report, handoff } = passing(f);
  const submitted = f.coordination.submit(f.id, data.state.revision, handoff.id, report);
  expect(deriveDeliveryProgress(submitted.state, submitted.coordination).next?.status).toBe("needs-review");
  return f.coordination.review(f.id, submitted.state.revision, handoff.milestoneId, "accept", "Reviewed the quoted fixture evidence; user acceptance only");
}
it("finishes a providerless finite loop, separates reports from acceptance, and survives restart", () => {
  const f = setup();
  for (let i = 0; i < 3; i++) acceptNext(f);
  let saved = f.coordination.read(f.id);
  expect(deriveDeliveryProgress(saved.state, saved.coordination)).toMatchObject({ readyForReview: true, next: undefined, unresolved: [] });
  expect(saved.state.plans).toHaveLength(1); expect(saved.state.nextPlans).toEqual([]);
  expect(f.db.prepare("SELECT * FROM delivery_generation").all()).toEqual([]);
  expect(saved.coordination.reports).toHaveLength(3); expect(saved.coordination.decisions).toHaveLength(3);
  f.db.close(); const reopened = openDb(f.dir); dbs.push(reopened);
  expect(deliveryCoordinationRepo(reopened).read(f.id)).toEqual(saved);
  const before = saved.state.revision;
  saved = deliveryCoordinationRepo(reopened).review(f.id, before, saved.coordination.handoffs[0]!.milestoneId, "return", "Regression found in an upstream capability");
  expect(saved.coordination.handoffs).toHaveLength(0);
  expect(deriveDeliveryProgress(saved.state, saved.coordination).milestones.map(m => m.status)).toEqual(["ready", "waiting", "waiting"]);
  expect(saved.coordination.reports).toHaveLength(3);
});
it("rejects stale, cross-project, tampered, changed-key and malformed results; retries the exact report", () => {
  const f = setup(), { data, report, handoff } = passing(f);
  for (const mutated of [{ ...report, projectId: "wrong" }, { ...report, planId: "wrong" }, { ...report, milestoneId: "wrong" }, { ...report, handoffId: "wrong" }, { ...report, criteria: report.criteria.slice(1) }, { ...report, criteria: [...report.criteria, report.criteria[0]] }]) expect(() => f.coordination.submit(f.id, data.state.revision, "bad", mutated)).toThrow();
  expect(() => f.coordination.submit(f.id, data.state.revision - 1, "stale", report)).toThrow(/changed/);
  const saved = f.coordination.submit(f.id, data.state.revision, "exact", report);
  expect(f.coordination.submit(f.id, data.state.revision, "exact", report)).toEqual(saved);
  expect(() => f.coordination.submit(f.id, saved.state.revision, "exact", { ...report, outcome: "Changed report" })).toThrow("Result key already used for different content");
  expect(saved.coordination.decisions).toEqual([]);
  f.coordination.review(f.id, saved.state.revision, handoff.milestoneId, "return", "Recheck against a fresh fixture");
  expect(() => f.coordination.submit(f.id, f.coordination.read(f.id).state.revision, "late", report)).toThrow("Result assignment is stale, blocked or belongs to another plan");
  expect(parseEvidenceResult(report)).toEqual(report);
  for (const bad of [{ ...report, extra: true }, { ...report, version: 2 }, { ...report, commands: [{ command: "test", exitCode: 0.5, evidence: "invalid" }] }, { ...report, outcome: "x".repeat(65000) }, { ...report, outcome: "api_key=private-value" }]) expect(() => parseEvidenceResult(bad)).toThrow();
  expect(() => parseFinishContract({ ...contract, criteria: [contract.criteria[0], contract.criteria[0]] })).toThrow();
});
it("fails closed on failed/unknown checks, explicit blockers, and missing prerequisites", () => {
  const f = setup(); let { data, report, handoff } = passing(f);
  report.criteria[0]!.status = "unknown";
  data = f.coordination.submit(f.id, data.state.revision, "unknown", report);
  expect(() => f.coordination.review(f.id, data.state.revision, handoff.milestoneId, "accept", "Cannot accept unknown evidence")).toThrow("Acceptance requires current, complete passing evidence and resolved prerequisites");
  report.criteria[0]!.status = "met"; report.commands[0]!.exitCode = 1;
  data = f.coordination.submit(f.id, data.state.revision, "failed", report);
  expect(() => f.coordination.review(f.id, data.state.revision, handoff.milestoneId, "accept", "Cannot accept failed checks")).toThrow("Acceptance requires current, complete passing evidence and resolved prerequisites");
  report.commands[0]!.exitCode = 0; report.blockers = ["Missing authorized pilot owner"];
  data = f.coordination.submit(f.id, data.state.revision, "blocked", report);
  expect(() => f.coordination.review(f.id, data.state.revision, handoff.milestoneId, "accept", "Cannot accept blockers")).toThrow("Acceptance requires current, complete passing evidence and resolved prerequisites");
  data = f.coordination.saveContract(f.id, data.state.revision, { ...contract, prerequisites: [{ text: "Authorize fixture use", owner: "Pilot owner", milestones: [0] }] });
  expect(deriveDeliveryProgress(data.state, data.coordination).next).toBeUndefined();
  expect(() => f.coordination.handoff(f.id, data.state.revision, handoff.milestoneId)).toThrow(/eligible/);
  data = f.coordination.resolve(f.id, data.state.revision, "p0", "Owner approved isolated synthetic fixtures");
  expect(deriveDeliveryProgress(data.state, data.coordination).next?.milestone.position).toBe(0);
});
it("lets independent work bypass a blocked branch and prevents goal changes resurrecting acceptance", () => {
  const f = setup();
  let data = f.coordination.saveManualPlan(f.id, f.state.state.revision, JSON.stringify({ ...draft, milestones: draft.milestones.map(m => ({ ...m, dependencies: [] })) }));
  const first = data.state.plans.at(-1)!.milestones[0]!;
  data = f.coordination.block(f.id, data.state.revision, first.id, "Awaiting an owner decision");
  expect(deriveDeliveryProgress(data.state, data.coordination).next?.milestone.position).toBe(1);
  acceptNext(f);
  const accepted = f.coordination.read(f.id);
  f.legacy.saveGoal(f.id, accepted.state.revision, { ...goal, provider: "openai", model: "gpt-6-astra" });
  expect(deriveDeliveryProgress(f.coordination.read(f.id).state, f.coordination.read(f.id).coordination).milestones[1]!.status).toBe("accepted");
  f.legacy.saveGoal(f.id, f.coordination.read(f.id).state.revision, { ...goal, workflow: "A different workflow" });
  expect(deriveDeliveryProgress(f.coordination.read(f.id).state, f.coordination.read(f.id).coordination).stale).toBe(true);
  f.legacy.saveGoal(f.id, f.coordination.read(f.id).state.revision, goal);
  expect(f.coordination.read(f.id).coordination.handoffs).toEqual([]);
});
it("keeps projects isolated, enforces revisions across connections, and rolls back multi-write failure", () => {
  const f = setup(), second = repo(f.db).ensureProject(path.join(f.dir, "second"), "Warehouse recovery", AT);
  f.legacy.saveGoal(second, 0, { ...goal, goal: "Warehouse shipment recovery" });
  f.coordination.saveContract(second, 1, contract); f.coordination.saveManualPlan(second, 2, JSON.stringify(draft));
  const { data, report } = passing(f);
  expect(() => f.coordination.submit(second, 3, "wrong-project", report)).toThrow();
  expect(f.coordination.read(second).coordination.reports).toEqual([]);
  const connection = openDb(f.dir); dbs.push(connection);
  f.coordination.focus(f.id, data.state.revision);
  expect(() => deliveryCoordinationRepo(connection).handoff(f.id, data.state.revision, report.milestoneId)).toThrow(/changed/);
  const before = f.coordination.read(f.id);
  f.db.exec("CREATE TRIGGER fail_review BEFORE INSERT ON delivery_reviews BEGIN SELECT RAISE(ABORT,'injected review failure'); END;");
  expect(() => f.coordination.review(f.id, before.state.revision, report.milestoneId, "return", "Injected rollback test")).toThrow(/injected/);
  expect(f.coordination.read(f.id)).toEqual(before);
  const prompt = coordinationAssignment({ projectName: "Synthetic enrollment", projectPath: "/fixture", state: before.state, coordination: before.coordination, handoff: before.coordination.handoffs[0]! });
  expect(prompt).toContain(report.handoffId); expect(prompt).toContain("UNTRUSTED DATA"); expect(prompt).not.toContain("Warehouse shipment recovery");
});
it("does not grandfather legacy reports into finish-line acceptance", () => {
  const f = setup();
  let state = f.legacy.read(f.id);
  for (const m of state.plans[0]!.milestones) state = f.legacy.complete(f.id, state.revision, m.id, `legacy-${m.position}`, { outcome: "Historical claim", evidence: "Unstructured report" }).state;
  const saved = f.coordination.saveContract(f.id, state.revision, contract);
  expect(saved.state.history.filter(e => e.kind === "complete")).toHaveLength(3);
  expect(saved.coordination.decisions).toEqual([]);
  expect(deriveDeliveryProgress(saved.state, saved.coordination).readyForReview).toBe(false);
  expect(deriveDeliveryProgress(saved.state, saved.coordination).milestones.map(m => m.status)).toEqual(["ready", "waiting", "waiting"]);
});
it("rolls a failed genuine v5 upgrade back without losing its goal", () => {
  const dir = home(), old = new DatabaseSync(path.join(dir, "pcc.db"));
  old.exec(fs.readFileSync(new URL("../src/db/schema.sql", import.meta.url), "utf8")); migrateDelivery(old);
  old.prepare("INSERT INTO schema_meta(version) VALUES (5)").run();
  const id = repo(old).ensureProject(path.join(dir, "preserved"), "Preserved", AT);
  old.prepare("INSERT INTO delivery_state(project_id,revision,goal_json,updated_at) VALUES (?,1,?,?)").run(id, JSON.stringify(goal), AT); old.close();
  expect(() => openDb(dir, () => { throw new Error("forced migration rollback"); })).toThrow("forced migration rollback");
  const checked = new DatabaseSync(path.join(dir, "pcc.db")); dbs.push(checked);
  expect(checked.prepare("SELECT version FROM schema_meta").get()).toMatchObject({ version: 5 });
  expect(checked.prepare("SELECT goal_json FROM delivery_state WHERE project_id=?").get(id)).toMatchObject({ goal_json: JSON.stringify(goal) });
  expect(checked.prepare("SELECT name FROM sqlite_schema WHERE name='delivery_contracts'").get()).toBeUndefined();
});
it("restores and upgrades a genuine populated v5 database without rewriting existing rows", () => {
  const dir = home(), backupDir = home();
  let db = new DatabaseSync(path.join(dir, "pcc.db"));
  db.exec(fs.readFileSync(new URL("../src/db/schema.sql", import.meta.url), "utf8")); migrateDelivery(db);
  db.exec("INSERT INTO schema_meta VALUES (5)");
  const id = repo(db).ensureProject("/synthetic/preserved", "Preserved", AT);
  db.prepare("INSERT INTO delivery_state(project_id,revision,goal_json,updated_at) VALUES (?,1,?,?)").run(id, JSON.stringify(goal), AT);
  db.prepare("INSERT INTO delivery_events(id,project_id,revision,kind,detail_json,source,created_at) VALUES ('original',?,1,'goal',?,'user-requested',?)").run(id, JSON.stringify(goal), AT);
  const before = db.prepare("SELECT * FROM delivery_events").all();
  db.prepare("VACUUM INTO ?").run(path.join(backupDir, "pcc.db")); db.close();
  const start = performance.now();
  expect(() => openDb(backupDir, () => { throw new Error("injected v6 failure"); })).toThrow("injected v6 failure");
  db = new DatabaseSync(path.join(backupDir, "pcc.db"));
  expect(db.prepare("SELECT version FROM schema_meta").get()).toMatchObject({ version: 5 });
  expect(db.prepare("SELECT name FROM sqlite_master WHERE name='delivery_contracts'").all()).toEqual([]); db.close();
  db = openDb(backupDir); dbs.push(db);
  expect(db.prepare("SELECT * FROM delivery_events").all()).toEqual(before);
  expect(db.prepare("SELECT version FROM schema_meta").get()).toMatchObject({ version: 6 });
  expect(db.prepare("PRAGMA integrity_check").get()).toMatchObject({ integrity_check: "ok" });
  expect(db.prepare("PRAGMA foreign_key_check").all()).toEqual([]);
  expect(deliveryRepo(db).read(id).goal).toEqual(goal);
  db.close(); db = openDb(backupDir); dbs.push(db);
  expect(db.prepare("SELECT * FROM delivery_events").all()).toEqual(before);
  console.info(`RUNTIME: v5 restore/rollback/v6 migration verified in ${Math.ceil(performance.now() - start)}ms`);
});
it("reviews only bounded contained nested documents and rejects changed reviews and excluded paths", async () => {
  const dir = home(); fs.mkdirSync(path.join(dir, "docs/operations"), { recursive: true });
  const file = path.join(dir, "docs/operations/readiness.md"); fs.writeFileSync(file, "Observed fixture readiness. ".repeat(180));
  const reviewed = await reviewDeliveryDocument(dir, "docs/operations/readiness.md"); expect(reviewed.excerptTruncated).toBe(true);
  for (const name of ["../README.md", "docs/operations/../readiness.md", "docs/operations/client.md", "docs/agent.md", "docs/.private/spec.md", "docs/a/b/c/d/spec.md", "/tmp/readiness.md"]) await expect(reviewDeliveryDocument(dir, name)).rejects.toThrow();
  const outside = home(); fs.writeFileSync(path.join(outside, "spec.md"), "outside"); fs.symlinkSync(path.join(outside, "spec.md"), path.join(dir, "docs/outside.md"));
  await expect(reviewDeliveryDocument(dir, "docs/outside.md")).rejects.toThrow();
  const input = { project: { id: "fixture", canonicalPath: dir }, goal, provider: "openai" as const, model: "gpt-6-astra", permissions: { collect: true as const, categories: ["goal", "documents"] as ("goal" | "documents")[], documents: [], additionalFiles: [{ path: reviewed.path, reviewedSha256: reviewed.reviewedSha256 }] } };
  expect((await collectDeliveryContext(input)).limitations.some(s => s.includes("truncated"))).toBe(true);
  fs.writeFileSync(file, "Changed observation"); await expect(collectDeliveryContext(input)).rejects.toThrow(/stale/);
  fs.writeFileSync(file, "api_key=private-value"); await expect(reviewDeliveryDocument(dir, reviewed.path)).rejects.toThrow();
});
